title: Annika Bergstrom 
description: I am an Educational and Scholarly Technology Assistant at Bryn Mawr College, passionate about supporting scholarship through innovation.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
